![alt text](./Cerny_logo_1.jpg)

# Analysis of Cerny ventilation recordings

#### Manual revision and trimming of ventilator recordings.

This notebook imports the preprocessed **Fabian ventilator parameters** data from pickle archive and performs trimming (removing periods when the patient was not connected to ventilator) based on manual inspection of data.

- At least 5 minutes of untrimmed ventilator and clinical data are available for **819 cases**
- At least 10 minutes of recording with **mechanical ventilation** is available after trimming in **407 cases**

The data processed and analysed in this Notebook were collected by the **Neonatal Emergency and Transport Service of the Peter Cerny Foundation**, Budapest, Hungary

**Author: Dr Gusztav Belteki**

### 1. Import the required libraries and set options

In [1]:
import IPython
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

import os
import sys
import pickle

from pandas import Series, DataFrame
from datetime import datetime, timedelta
from matplotlib import dates

%matplotlib inline
matplotlib.style.use('classic')
matplotlib.rcParams['figure.facecolor'] = 'w'

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
# pd.set_option('mode.chained_assignment', None)

import warnings
warnings.simplefilter("ignore")

In [2]:
print("Python version: {}".format(sys.version))
print("pandas version: {}".format(pd.__version__))
print("matplotlib version: {}".format(matplotlib.__version__))
print("NumPy version: {}".format(np.__version__))
print("IPython version: {}".format(IPython.__version__))

Python version: 3.12.11 | packaged by conda-forge | (main, Jun  4 2025, 14:38:53) [Clang 18.1.8 ]
pandas version: 2.3.2
matplotlib version: 3.10.6
NumPy version: 1.26.4
IPython version: 9.5.0

### 2. List and set the working directory and the directory to write out data

In [4]:
# Name of the external hard drive
DRIVE = 'GB_1'

# Path to project folder containing ventilation research results
PATH = os.path.join(os.sep, 'Users', 'guszti', 'Library', 'Mobile Documents', 'com~apple~CloudDocs', 
                            'Documents', 'Research', 'Ventilation')

# Folder to export the result of analysis
DIR_WRITE = os.path.join(PATH, 'ventilation_fabian', 'Analyses', 'analysis_1_1100')
os.makedirs(DIR_WRITE, exist_ok = True)

# Folder on a USB stick to export data to and to import processed data exported by other Notebooks
DATA_DUMP = os.path.join(os.sep, 'Volumes', DRIVE, 'data_dump', 'fabian',)
os.makedirs(DATA_DUMP, exist_ok = True)

DIR_WRITE, DATA_DUMP

('/Users/guszti/Library/Mobile Documents/com~apple~CloudDocs/Documents/Research/Ventilation/ventilation_fabian/Analyses/analysis_1_1100',
 '/Volumes/GB_1/data_dump/fabian')

### 3. Import ventilator data from pickle archives

In [6]:
with open(os.path.join(DATA_DUMP, 'data_pars_measurements_1_1100.pickle'), 'rb') as handle:
    data_pars_measurements = pickle.load(handle)   
with open(os.path.join(DATA_DUMP, 'data_pars_settings_1_1100.pickle'), 'rb') as handle:
    data_pars_settings = pickle.load(handle)  
with open(os.path.join(DATA_DUMP, 'data_pars_alarms_1_1100.pickle'), 'rb') as handle:
    data_pars_alarms = pickle.load(handle)
len(data_pars_measurements)

819

### 4. Exploratory analysis on ventilation modes

##### How many cases of the different ventilation modes occur

In [9]:
vent_modes = {}
for case in data_pars_settings:
    # Multiply by two to get the number of seconds
    vent_modes[case] = data_pars_settings[case]['Ventilator_mode'].value_counts() * 2
vent_modes = DataFrame(vent_modes).T
vent_modes.replace(np.nan, 0, inplace = True)

In [13]:
# Add the duration of the recordings
recording_duration = {}
for case in data_pars_settings:
    recording_duration[case] = 2 * len(data_pars_settings[case])

In [14]:
vent_modes['ventilation'] = vent_modes['IPPV'] + vent_modes['SIMV'] + vent_modes['SIPPV'] + vent_modes['SIMVPSV']
vent_modes['noninvasive'] = vent_modes['CPAP'] + vent_modes['DUOPAP'] + vent_modes['NCPAP'] + vent_modes['O2therapy']  
vent_modes['total'] = Series(recording_duration)

In [15]:
print('SIMV:', sum(vent_modes['SIMV'] > 0))
print('SIPPV:', sum(vent_modes['SIPPV'] > 0))
print('SIMVPSV:', sum(vent_modes['SIMVPSV'] > 0))
print('PSV:', sum(vent_modes['PSV'] > 0))
print('IPPV:', sum(vent_modes['IPPV'] > 0))
print('NCPAP:', sum(vent_modes['NCPAP'] > 0))
print('CPAP:', sum(vent_modes['CPAP'] > 0))
print('DUOPAP:', sum(vent_modes['DUOPAP'] > 0))
print('O2therapy:', sum(vent_modes['O2therapy'] > 0))
print('ventilation:', sum(vent_modes['ventilation'] > 0))
print('noninvasive:', sum(vent_modes['noninvasive'] > 0))
print('total', len(vent_modes))

SIMV: 435
SIPPV: 255
SIMVPSV: 69
PSV: 4
IPPV: 95
NCPAP: 450
CPAP: 16
DUOPAP: 106
O2therapy: 132
ventilation: 625
noninvasive: 590
total 819

In [16]:
# How many seconds of each ventilation mode in total?
total_duration = DataFrame(vent_modes.sum(axis = 0), columns = ['duration (seconds)'])
total_duration

                 duration (seconds)
Ventilator_mode
CPAP                         3634.0
DUOPAP                     199362.0
IPPV                        61136.0
NCPAP                     1024542.0
O2therapy                  271090.0
PSV                           264.0
SIMV                      1199432.0
SIMVPSV                    100132.0
SIPPV                      636658.0
ventilation               1997358.0
noninvasive               1498628.0
total                     3496250.0

##### Export Dataframes containing ventilator modes to Excel files and pickle archives

In [18]:
writer = pd.ExcelWriter(os.path.join(DIR_WRITE, 'ventilation_modes_1_1100.xlsx'))
vent_modes.to_excel(writer, 'vent_modes')
total_duration.to_excel(writer, 'total_duration')
writer.close()

In [19]:
with open(os.path.join(DATA_DUMP, 'vent_modes_1_1100'), 'wb') as handle:
    pickle.dump(vent_modes, handle, protocol=pickle.HIGHEST_PROTOCOL)

### 5. Only consider those recordings that have at least 10 minutes (600 seconds) mechanical ventilation

In [21]:
# Sampling rate is 0.5 Hz
vent_modes_ventilated = vent_modes[vent_modes['ventilation'] >= 600]
len(vent_modes_ventilated)

418

In [39]:
vent_modes_ventilated.head(100)

Ventilator_mode,CPAP,DUOPAP,IPPV,NCPAP,O2therapy,PSV,SIMV,SIMVPSV,SIPPV,ventilation,noninvasive,total
AL000003,0.0,0.0,0.0,4.0,0.0,0.0,6294.0,0.0,0.0,6294.0,4.0,6298
AL000006,0.0,0.0,0.0,164.0,0.0,0.0,8.0,2834.0,0.0,2842.0,164.0,3006
AL000007,0.0,0.0,0.0,0.0,0.0,0.0,7156.0,74.0,0.0,7230.0,0.0,7230
AL000008,0.0,0.0,0.0,0.0,0.0,0.0,6762.0,0.0,0.0,6762.0,0.0,6762
AL000009,0.0,0.0,0.0,0.0,0.0,0.0,42.0,0.0,2756.0,2798.0,0.0,2798
AL000011,0.0,0.0,0.0,16.0,0.0,0.0,5778.0,0.0,0.0,5778.0,16.0,5794
AL000014,0.0,0.0,0.0,2.0,0.0,0.0,3636.0,0.0,0.0,3636.0,2.0,3638
AL000018,0.0,0.0,0.0,120.0,0.0,0.0,0.0,2708.0,0.0,2708.0,120.0,2828
AL000019,0.0,0.0,0.0,0.0,0.0,0.0,2758.0,14.0,0.0,2772.0,0.0,2772
AL000020,0.0,0.0,0.0,0.0,0.0,0.0,204.0,0.0,7860.0,8064.0,0.0,8064
AL000021,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6608.0,6608.0,0.0,6608
AL000022,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2138.0,2138.0,0.0,2138
AL000023,0.0,0.0,0.0,0.0,0.0,0.0,3432.0,0.0,48.0,3480.0,0.0,3480
AL000024,0.0,0.0,0.0,0.0,0.0,0.0,26.0,0.0,3992.0,4018.0,0.0,4018
AL000026,0.0,0.0,0.0,8.0,0.0,0.0,12628.0,0.0,0.0,12628.0,8.0,12636
AL000028,0.0,0.0,0.0,0.0,0.0,0.0,5552.0,0.0,0.0,5552.0,0.0,5552
AL000029,0.0,0.0,0.0,0.0,0.0,0.0,2924.0,0.0,0.0,2924.0,0.0,2924
AL000030,0.0,0.0,508.0,0.0,0.0,0.0,5314.0,0.0,0.0,5822.0,0.0,5822
AL000033,0.0,4.0,0.0,0.0,0.0,0.0,3430.0,0.0,0.0,3430.0,4.0,3434
AL000034,0.0,0.0,0.0,0.0,0.0,0.0,32.0,0.0,5956.0,5988.0,0.0,5988
AL000035,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2544.0,2544.0,0.0,2544
AL000036,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5262.0,5262.0,0.0,5262
AL000037,0.0,0.0,0.0,0.0,0.0,0.0,1972.0,0.0,86.0,2058.0,0.0,2058
AL000038,0.0,0.0,0.0,0.0,0.0,0.0,5944.0,0.0,0.0,5944.0,0.0,5944
AL000041,0.0,0.0,38.0,0.0,0.0,0.0,2012.0,0.0,0.0,2050.0,0.0,2050
AL000042,0.0,0.0,2574.0,0.0,0.0,0.0,78.0,0.0,0.0,2652.0,0.0,2652
AL000043,0.0,0.0,1410.0,0.0,0.0,0.0,0.0,0.0,0.0,1410.0,0.0,1410
AL000044,0.0,0.0,38.0,0.0,0.0,0.0,3034.0,0.0,0.0,3072.0,0.0,3072
AL000048,0.0,1118.0,0.0,0.0,0.0,0.0,5850.0,0.0,0.0,5850.0,1118.0,6968
AL000052,0.0,0.0,0.0,2.0,0.0,0.0,6614.0,0.0,0.0,6614.0,2.0,6616
AL000054,0.0,0.0,0.0,12.0,0.0,0.0,3064.0,0.0,0.0,3064.0,12.0,3076
AL000055,0.0,0.0,0.0,0.0,0.0,0.0,38.0,0.0,5558.0,5596.0,0.0,5596
AL000056,0.0,0.0,0.0,0.0,0.0,0.0,7556.0,0.0,1344.0,8900.0,0.0,8900
AL000057,0.0,0.0,0.0,0.0,8.0,0.0,3244.0,0.0,0.0,3244.0,8.0,3252
AL000059,0.0,0.0,0.0,36.0,0.0,0.0,600.0,74.0,0.0,674.0,36.0,710
AL000060,0.0,0.0,0.0,0.0,0.0,0.0,2220.0,146.0,0.0,2366.0,0.0,2366
AL000061,0.0,0.0,0.0,0.0,0.0,0.0,2148.0,0.0,0.0,2148.0,0.0,2148
AL000064,382.0,0.0,10.0,0.0,0.0,0.0,0.0,3036.0,0.0,3046.0,382.0,3428
AL000066,0.0,0.0,0.0,4.0,0.0,0.0,4882.0,0.0,0.0,4882.0,4.0,4886
AL000067,0.0,0.0,0.0,0.0,0.0,0.0,8354.0,0.0,0.0,8354.0,0.0,8354
AL000072,0.0,0.0,0.0,172.0,0.0,0.0,4668.0,0.0,0.0,4668.0,172.0,4840
AL000074,0.0,0.0,0.0,0.0,0.0,0.0,6562.0,0.0,0.0,6562.0,0.0,6562
AL000075,0.0,0.0,0.0,0.0,0.0,0.0,5318.0,0.0,0.0,5318.0,0.0,5318
AL000077,0.0,106.0,184.0,48.0,0.0,0.0,0.0,0.0,2862.0,3046.0,154.0,3200
AL000079,0.0,0.0,0.0,0.0,0.0,0.0,1540.0,0.0,1268.0,2808.0,0.0,2808
AL000080,0.0,0.0,0.0,0.0,0.0,0.0,4628.0,0.0,26.0,4654.0,0.0,4654
AL000081,0.0,0.0,0.0,0.0,0.0,0.0,368.0,0.0,2946.0,3314.0,0.0,3314
AL000084,0.0,0.0,6878.0,0.0,34.0,0.0,0.0,0.0,0.0,6878.0,34.0,6912
AL000085,0.0,0.0,3942.0,0.0,0.0,0.0,0.0,0.0,0.0,3942.0,0.0,3942
AL000089,0.0,0.0,118.0,102.0,0.0,0.0,2596.0,0.0,1562.0,4276.0,102.0,4378
AL000090,0.0,0.0,0.0,0.0,0.0,0.0,6870.0,0.0,16.0,6886.0,0.0,6886
AL000097,0.0,0.0,0.0,106.0,0.0,0.0,1660.0,0.0,0.0,1660.0,106.0,1766
AL000098,0.0,0.0,0.0,0.0,0.0,0.0,5670.0,0.0,0.0,5670.0,0.0,5670
AL000099,0.0,0.0,0.0,0.0,0.0,0.0,44.0,0.0,2596.0,2640.0,0.0,2640
AL000100,0.0,0.0,688.0,0.0,0.0,0.0,0.0,0.0,1910.0,2598.0,0.0,2598
AL000101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2506.0,2506.0,0.0,2506
AL000103,0.0,0.0,0.0,52.0,0.0,0.0,6472.0,0.0,0.0,6472.0,52.0,6524
AL000104,0.0,0.0,0.0,0.0,0.0,0.0,3536.0,0.0,5694.0,9230.0,0.0,9230
AL000105,0.0,0.0,0.0,0.0,0.0,0.0,3314.0,0.0,2696.0,6010.0,0.0,6010
AL000106,0.0,0.0,0.0,0.0,0.0,0.0,4078.0,0.0,100.0,4178.0,0.0,4178
AL000110,0.0,0.0,0.0,0.0,68.0,0.0,74.0,0.0,7576.0,7650.0,68.0,7718
AL000111,0.0,0.0,0.0,0.0,0.0,0.0,6270.0,0.0,46.0,6316.0,0.0,6316
AL000112,0.0,0.0,0.0,0.0,0.0,0.0,8520.0,0.0,0.0,8520.0,0.0,8520
AL000113,0.0,0.0,0.0,0.0,0.0,0.0,15676.0,0.0,0.0,15676.0,0.0,15676
AL000114,0.0,0.0,0.0,0.0,0.0,0.0,32.0,6682.0,0.0,6714.0,0.0,6714
AL000115,0.0,0.0,0.0,0.0,0.0,0.0,0.0,128.0,8460.0,8588.0,0.0,8588
AL000116,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4830.0,4830.0,0.0,4830
AL000117,0.0,0.0,0.0,0.0,0.0,0.0,4894.0,0.0,1270.0,6164.0,0.0,6164
AL000118,0.0,0.0,0.0,0.0,0.0,0.0,18.0,6432.0,0.0,6450.0,0.0,6450
AL000119,0.0,0.0,0.0,0.0,0.0,0.0,2146.0,44.0,1402.0,3592.0,0.0,3592
AL000120,0.0,0.0,0.0,0.0,0.0,0.0,9244.0,0.0,2094.0,11338.0,0.0,11338
AL000121,0.0,0.0,0.0,0.0,0.0,0.0,7472.0,0.0,0.0,7472.0,0.0,7472
AL000123,0.0,0.0,74.0,0.0,0.0,0.0,0.0,2478.0,0.0,2552.0,0.0,2552
AL000126,0.0,0.0,18.0,6.0,0.0,0.0,8046.0,0.0,0.0,8064.0,6.0,8070
AL000127,0.0,0.0,0.0,0.0,0.0,0.0,5470.0,0.0,0.0,5470.0,0.0,5470
AL000132,0.0,0.0,0.0,38.0,0.0,0.0,2776.0,0.0,0.0,2776.0,38.0,2814
AL000135,0.0,0.0,1506.0,0.0,36.0,0.0,0.0,0.0,0.0,1506.0,36.0,1542
AL000138,0.0,0.0,0.0,2.0,0.0,0.0,3384.0,0.0,0.0,3384.0,2.0,3386
AL000140,0.0,0.0,0.0,4.0,0.0,0.0,68.0,0.0,6564.0,6632.0,4.0,6636
AL000141,0.0,0.0,0.0,0.0,0.0,0.0,5688.0,0.0,8.0,5696.0,0.0,5696
AL000142,0.0,0.0,7300.0,0.0,0.0,0.0,0.0,0.0,0.0,7300.0,0.0,7300
AL000144,0.0,0.0,0.0,48.0,0.0,0.0,718.0,6030.0,0.0,6748.0,48.0,6796
AL000146,36.0,0.0,0.0,6.0,0.0,0.0,3270.0,0.0,0.0,3270.0,42.0,3312
AL000148,0.0,0.0,0.0,0.0,0.0,0.0,2884.0,0.0,0.0,2884.0,0.0,2884
AL000149,0.0,0.0,0.0,0.0,0.0,0.0,4934.0,0.0,0.0,4934.0,0.0,4934
AL000152,0.0,0.0,0.0,0.0,0.0,0.0,4032.0,3706.0,204.0,7942.0,0.0,7942
AL000154,0.0,0.0,0.0,0.0,0.0,0.0,4626.0,318.0,0.0,4944.0,0.0,4944
AL000156,0.0,0.0,0.0,14.0,0.0,0.0,2554.0,0.0,0.0,2554.0,14.0,2568
AL000157,0.0,0.0,0.0,0.0,0.0,0.0,4004.0,0.0,0.0,4004.0,0.0,4004
AL000158,0.0,0.0,0.0,0.0,0.0,0.0,6570.0,36.0,0.0,6606.0,0.0,6606
AL000159,0.0,0.0,0.0,1894.0,0.0,0.0,1038.0,508.0,0.0,1546.0,1894.0,3440
AL000161,0.0,0.0,0.0,140.0,0.0,0.0,3840.0,0.0,0.0,3840.0,140.0,3980
AL000162,0.0,0.0,0.0,0.0,0.0,0.0,5052.0,0.0,0.0,5052.0,0.0,5052
AL000165,0.0,0.0,0.0,0.0,98.0,0.0,4542.0,0.0,18.0,4560.0,98.0,4658
AL000172,0.0,0.0,0.0,16.0,0.0,0.0,4692.0,0.0,0.0,4692.0,16.0,4708
AL000174,0.0,0.0,0.0,8.0,0.0,0.0,3126.0,0.0,0.0,3126.0,8.0,3134
AL000175,0.0,0.0,0.0,0.0,0.0,0.0,5776.0,8.0,0.0,5784.0,0.0,5784
AL000176,0.0,0.0,0.0,0.0,0.0,0.0,4340.0,0.0,0.0,4340.0,0.0,4340
AL000179,0.0,0.0,0.0,14.0,0.0,0.0,6370.0,0.0,0.0,6370.0,14.0,6384
AL000181,0.0,0.0,88.0,0.0,0.0,0.0,8864.0,0.0,0.0,8952.0,0.0,8952

### 6. Remove the periods from the beginning and the end of the recordings when the patient was not connected to the ventilator

This requires manual inspection of the tidal volume and pressure graphs

This dictionary contains tuples of the start and end points as strings
This was obtained by manual inspection of VTmand and PIP and the recordings
and manually removing the start and the end when the baby was not on the ventilator (e.g. no VTmand)

In [35]:
with open(os.path.join(DATA_DUMP, 'limit_1_1100_ventilated.pickle'), 'rb') as handle:
    limit = pickle.load(handle)

In [37]:
limit

{'AL000064': ('2017-06-13 18:46:30', '2017-06-13 19:29:00'),
 'AL000003': ('2017-03-24 18:22:00', '2017-03-24 19:48:00'),
 'AL000114': ('2017-08-03 09:13:00', '2017-08-03 10:50:00'),
 'AL000285': ('2018-06-29 15:54:00', '2018-06-29 16:32:30'),
 'AL000118': ('2017-08-08 09:01:00', '2017-08-08 10:44:00'),
 'AL000268': ('2018-06-14 10:39:00', '2018-06-14 12:09:00'),
 'AL000090': ('2017-07-13 10:19:00', '2017-07-13 12:09:29'),
 'AL000018': ('2017-04-13 15:55:00', '2017-04-13 16:32:00'),
 'AL000246': ('2018-04-11 19:24:00', '2018-04-11 21:25:00'),
 'AL000035': ('2017-04-27 09:03:00', '2017-04-27 09:41:00'),
 'AL000284': ('2018-06-29 12:26:30', '2018-06-29 13:07:30'),
 'AL000215': ('2018-03-19 21:36:00', '2018-03-19 22:09:00'),
 'AL000279': ('2018-06-24 11:17:00', '2018-06-24 13:04:00'),
 'AL000176': ('2017-12-10 23:00:00', '2017-12-11 00:03:00'),
 'AL000067': ('2017-06-14 22:29:00', '2017-06-15 00:45:00'),
 'AL000048': ('2017-05-09 05:50:00', '2017-05-09 07:24:00'),
 'AL000250': ('2018-04-14 17:47:30', '2018-04-14 18:43:00'),
 'AL000100': ('2017-07-24 08:44:30', '2017-07-24 09:17:00'),
 'AL000099': ('2017-07-23 15:18:00', '2017-07-23 15:51:00'),
 'AL000036': ('2017-04-28 02:07:00', '2017-04-28 03:13:00'),
 'AL000146': ('2017-08-31 10:36:00', '2017-08-31 11:27:00'),
 'AL000148': ('2017-08-31 20:50:00', '2017-08-31 21:34:00'),
 'AL000033': ('2017-04-26 09:38:00', '2017-04-26 10:26:00'),
 'AL000152': ('2017-11-19 08:20:00', '2017-11-19 10:19:00'),
 'AL000277': ('2018-06-22 12:28:30', '2018-06-22 14:06:00'),
 'AL000116': ('2017-08-05 20:54:00', '2017-08-05 22:09:00'),
 'AL000288': ('2018-06-30 20:23:00', '2018-06-30 20:48:00'),
 'AL000296': ('2018-07-16 12:23:00', '2018-07-16 13:55:30'),
 'AL000132': ('2017-08-19 18:33:00', '2017-08-19 19:12:00'),
 'AL000028': ('2017-04-21 13:15:00', '2017-04-21 14:11:00'),
 'AL000126': ('2017-08-17 03:32:00', '2017-08-17 05:35:00'),
 'AL000175': ('2017-12-08 20:00:00', '2017-12-08 21:25:00'),
 'AL000022': ('2017-04-17 09:28:00', '2017-04-17 10:00:30'),
 'AL000135': ('2017-08-21 21:54:00', '2017-08-21 22:16:00'),
 'AL000006': ('2017-03-27 00:16:00', '2017-03-27 00:54:00'),
 'AL000034': ('2017-04-26 22:52:00', '2017-04-27 00:25:00'),
 'AL000117': ('2017-08-17 03:32:00', '2017-08-17 05:35:00'),
 'AL000119': ('2017-08-08 13:44:00', '2017-08-08 14:38:00'),
 'AL000057': ('2017-06-08 05:03:00', '2017-06-08 05:53:00'),
 'AL000181': ('2017-12-12 10:42:30', '2017-12-12 12:45:00'),
 'AL000159': ('2017-11-24 08:07:00', '2017-11-24 08:32:16'),
 'AL000055': ('2017-05-19 15:36:00', '2017-05-19 17:05:00'),
 'AL000123': ('2017-08-15 04:07:30', '2017-08-15 04:36:30'),
 'AL000014': ('2017-04-06 19:07:00', '2017-04-06 19:46:00'),
 'AL000066': ('2017-06-14 10:56:00', '2017-06-14 12:13:00'),
 'AL000085': ('2017-07-06 14:25:00', '2017-07-06 15:21:00'),
 'AL000267': ('2018-06-08 19:41:00', '2018-06-08 22:10:00'),
 'AL000081': ('2017-07-03 03:58:00', '2017-07-03 04:50:00'),
 'AL000206': ('2018-03-07 14:37:00', '2018-03-07 15:02:00'),
 'AL000009': ('2017-03-31 05:46:00', '2017-03-31 06:23:30'),
 'AL000227': ('2018-03-28 09:58:00', '2018-03-28 11:05:00'),
 'AL000212': ('2018-03-15 15:08:00', '2018-03-15 16:10:00'),
 'AL000024': ('2017-04-18 02:26:00', '2017-04-18 03:23:00'),
 'AL000115': ('2017-08-05 12:03:00', '2017-08-05 14:19:00'),
 'AL000161': ('2017-11-24 16:47:00', '2017-11-24 17:55:34'),
 'AL000172': ('2017-12-07 09:54:00', '2017-12-07 11:08:00'),
 'AL000075': ('2017-06-27 14:09:00', '2017-06-27 15:40:00'),
 'AL000044': ('2017-05-06 11:59:00', '2017-05-06 12:43:30'),
 'AL000156': ('2017-11-21 20:19:00', '2017-11-21 20:45:00'),
 'AL000300': ('2018-07-20 06:07:30', '2018-07-20 06:50:00'),
 'AL000149': ('2017-09-02 08:11:00', '2017-09-02 09:24:00'),
 'AL000271': ('2018-06-16 16:34:00', '2018-06-16 16:54:00'),
 'AL000245': ('2018-04-11 14:03:00', '2018-04-11 15:34:00'),
 'AL000072': ('2017-06-24 03:13:00', '2017-06-24 04:27:00'),
 'AL000110': ('2017-07-30 22:55:00', '2017-07-31 00:50:00'),
 'AL000020': ('2017-04-14 13:05:00', '2017-04-14 15:02:00'),
 'AL000141': ('2017-08-27 02:08:00', '2017-08-27 03:36:00'),
 'AL000219': ('2018-03-26 01:04:00', '2018-03-26 01:56:00'),
 'AL000021': ('2017-04-15 18:55:00', '2017-04-15 20:21:00'),
 'AL000283': ('2018-06-26 08:54:30', '2018-06-26 11:05:00'),
 'AL000158': ('2017-11-23 11:21:00', '2017-11-23 12:39:00'),
 'AL000038': ('2017-04-29 09:34:00', '2017-04-29 10:56:00'),
 'AL000179': ('2017-12-11 14:13:00', '2017-12-11 15:53:00'),
 'AL000041': ('2017-04-30 10:12:00', '2017-04-30 10:42:00'),
 'AL000121': ('2017-08-09 13:25:00', '2017-08-09 15:23:00'),
 'AL000157': ('2017-11-22 09:59:06', '2017-11-22 11:04:00'),
 'AL000234': ('2018-04-06 01:54:30', '2018-04-06 02:33:00'),
 'AL000223': ('2018-03-27 07:44:30', '2018-03-27 09:17:30'),
 'AL000165': ('2017-11-28 12:50:00', '2017-11-28 14:03:00'),
 'AL000056': ('2017-05-21 12:50:00', '2017-05-21 15:10:00'),
 'AL000162': ('2017-11-25 11:00:00', '2017-11-25 12:17:00'),
 'AL000286': ('2018-06-29 21:33:00', '2018-06-29 22:54:00'),
 'AL000105': ('2017-07-26 03:25:00', '2017-07-26 05:01:00'),
 'AL000042': ('2017-05-02 19:47:00', '2017-05-02 20:20:00'),
 'AL000029': ('2017-04-21 17:39:00', '2017-04-21 18:26:00'),
 'AL000043': ('2017-05-02 20:49:00', '2017-05-02 21:11:00'),
 'AL000280': ('2018-06-24 22:12:30', '2018-06-24 23:21:00'),
 'AL000089': ('2017-07-11 16:15:00', '2017-07-11 17:13:00'),
 'AL000023': ('2017-04-17 23:24:00', '2017-04-18 00:13:00'),
 'AL000037': ('2017-04-28 12:02:30', '2017-04-28 12:24:00'),
 'AL000080': ('2017-07-02 04:35:00', '2017-07-02 05:50:00'),
 'AL000030': ('2017-04-21 19:40:00', '2017-04-21 20:20:00'),
 'AL000106': ('2017-07-26 09:44:00', '2017-07-26 10:45:30'),
 'AL000098': ('2017-07-19 16:48:00', '2017-07-19 18:20:00'),
 'AL000244': ('2018-04-10 10:30:00', '2018-04-10 12:33:00'),
 'AL000239': ('2018-04-07 16:04:00', '2018-04-07 17:48:00'),
 'AL000077': ('2017-06-28 16:14:00', '2017-06-28 17:01:00'),
 'AL000188': ('2017-12-18 15:17:00', '2017-12-18 16:02:00'),
 'AL000079': ('2017-07-01 04:34:00', '2017-07-01 05:18:00'),
 'AL000113': ('2017-08-03 01:22:00', '2017-08-03 05:18:47'),
 'AL000193': ('2017-12-20 17:44:00', '2017-12-20 19:10:00'),
 'AL000264': ('2018-06-07 17:22:00', '2018-06-07 19:18:00'),
 'AL000127': ('2017-08-17 09:55:00', '2017-08-17 11:13:00'),
 'AL000103': ('2017-07-25 02:23:00', '2017-07-25 04:06:00'),
 'AL000251': ('2018-04-15 00:20:00', '2018-04-15 01:22:00'),
 'AL000154': ('2017-11-21 10:42:00', '2017-11-21 11:52:00'),
 'AL000054': ('2017-05-19 09:11:30', '2017-05-19 09:58:00'),
 'AL000187': ('2017-12-18 07:42:00', '2017-12-18 08:15:30'),
 'AL000291': ('2018-07-03 16:35:00', '2018-07-03 18:05:34'),
 'AL000294': ('2018-07-10 12:30:30', '2018-07-10 13:10:30'),
 'AL000241': ('2018-04-08 16:50:00', '2018-04-08 17:20:30'),
 'AL000261': ('2018-06-06 10:28:00', '2018-06-06 10:57:30'),
 'AL000221': ('2018-03-26 20:47:00', '2018-03-26 21:20:30'),
 'AL000140': ('2017-08-25 13:28:00', '2017-08-25 15:12:00'),
 'AL000240': ('2018-04-08 09:52:00', '2018-04-08 11:39:00'),
 'AL000174': ('2017-12-08 10:53:30', '2017-12-08 11:28:00'),
 'AL000084': ('2017-07-06 09:51:00', '2017-07-06 11:43:00'),
 'AL000204': ('2018-03-07 04:10:00', '2018-03-07 04:35:30'),
 'AL000247': ('2018-04-12 21:05:00', '2018-04-12 22:36:00'),
 'AL000052': ('2017-05-16 22:11:00', '2017-05-16 23:56:00'),
 'AL000104': ('2017-07-25 19:00:00', '2017-07-25 21:22:00'),
 'AL000061': ('2017-06-12 12:20:00', '2017-06-12 12:49:30'),
 'AL000289': ('2018-07-01 04:32:00', '2018-07-01 05:31:30'),
 'AL000111': ('2017-08-01 10:24:00', '2017-08-01 12:05:00'),
 'AL000142': ('2017-08-27 12:08:00', '2017-08-27 14:01:00'),
 'AL000229': ('2018-03-29 10:33:30', '2018-03-29 12:14:00'),
 'AL000273': ('2018-06-17 13:45:00', '2018-06-17 14:28:30'),
 'AL000074': ('2017-06-24 17:03:00', '2017-06-24 18:49:00'),
 'AL000226': ('2018-03-27 23:35:00', '2018-03-28 02:15:00'),
 'AL000295': ('2018-07-16 01:33:00', '2018-07-16 02:50:00'),
 'AL000138': ('2017-08-24 02:32:00', '2017-08-24 03:13:30'),
 'AL000112': ('2017-08-02 18:55:00', '2017-08-02 21:11:00'),
 'AL000274': ('2018-06-19 13:54:00', '2018-06-19 14:42:00'),
 'AL000293': ('2018-07-08 09:40:00', '2018-07-08 10:18:30'),
 'AL000008': ('2017-03-29 15:50:00', '2017-03-29 17:34:00'),
 'AL000192': ('2017-12-20 13:42:00', '2017-12-20 15:12:17'),
 'AL000281': ('2018-06-25 00:51:30', '2018-06-25 01:37:30'),
 'AL000026': ('2017-04-20 12:15:00', '2017-04-20 15:37:00'),
 'AL000101': ('2017-07-24 11:11:30', '2017-07-24 11:48:30'),
 'AL000007': ('2017-03-29 00:55:00', '2017-03-29 02:46:00'),
 'AL000097': ('2017-07-19 09:10:00', '2017-07-19 09:36:00'),
 'AL000060': ('2017-06-10 20:02:00', '2017-06-10 20:34:00'),
 'AL000144': ('2017-08-29 13:20:00', '2017-08-29 15:03:00'),
 'AL000011': ('2017-04-01 00:20:00', '2017-04-01 01:50:00'),
 'AL000120': ('2017-08-08 21:48:00', '2017-08-09 00:50:00'),
 'AL000019': ('2017-04-14 02:58:00', '2017-04-14 03:35:00'),
 'AL000307': ('2018-07-26 11:30:00', '2018-07-26 13:08:00'),
 'AL000302': ('2018-07-23 23:41:00', '2018-07-24 01:16:00'),
 'AL000360': ('2018-09-06 08:44:30', '2018-09-06 09:21:30'),
 'AL000348': ('2018-08-28 15:39:30', '2018-08-28 16:20:00'),
 'AL000339': ('2018-08-21 07:49:00', '2018-08-21 08:18:30'),
 'AL000328': ('2018-08-12 12:21:00', '2018-08-12 12:54:00'),
 'AL000357': ('2018-09-03 17:29:00', '2018-09-03 18:04:00'),
 'AL000366': ('2018-09-07 17:22:30', '2018-09-07 19:21:00'),
 'AL000327': ('2018-08-12 06:24:00', '2018-08-12 08:07:00'),
 'AL000365': ('2018-09-07 14:47:00', '2018-09-07 15:19:00'),
 'AL000301': ('2018-07-20 10:28:00', '2018-07-20 11:50:00'),
 'AL000342': ('2018-08-24 11:28:00', '2018-08-24 15:03:00'),
 'AL000316': ('2018-08-02 13:44:00', '2018-08-02 15:07:00'),
 'AL000315': ('2018-08-02 11:28:00', '2018-08-02 11:56:00'),
 'AL000330': ('2018-08-13 03:21:00', '2018-08-13 04:53:00'),
 'AL000362': ('2018-09-06 16:08:00', '2018-09-06 18:00:00'),
 'AL000344': ('2018-08-26 07:38:00', '2018-08-26 09:44:00'),
 'AL000331': ('2018-08-15 07:00:00', '2018-08-15 09:05:00'),
 'AL000353': ('2018-08-31 10:41:00', '2018-08-31 11:27:33'),
 'AL000355': ('2018-09-02 11:47:00', '2018-09-02 12:57:00'),
 'AL000358': ('2018-09-05 06:04:00', '2018-09-05 06:58:00'),
 'AL000310': ('2018-07-29 20:54:30', '2018-07-29 22:52:00'),
 'AL000386': ('2018-11-08 08:24:30', '2018-11-08 08:51:30'),
 'AL000387': ('2018-11-08 11:10:30', '2018-11-08 11:53:00'),
 'AL000390': ('2018-11-23 07:02:00', '2018-11-23 07:49:00'),
 'AL000393': ('2018-11-23 11:49:00', '2018-11-23 12:22:30'),
 'AL000395': ('2018-11-24 00:08:30', '2018-11-24 01:00:00'),
 'AL000396': ('2018-11-24 14:03:00', '2018-11-24 14:53:00'),
 'AL000400': ('2018-11-28 00:10:30', '2018-11-28 01:22:00'),
 'AL000402': ('2018-11-28 11:15:00', '2018-11-28 13:19:00'),
 'AL000405': ('2018-11-30 05:50:00', '2018-11-30 07:39:30'),
 'AL000406': ('2018-11-30 12:38:00', '2018-11-30 13:41:00'),
 'AL000410': ('2018-12-04 00:43:30', '2018-12-04 02:35:00'),
 'AL000425': ('2018-12-02 13:59:00', '2018-12-02 16:03:00'),
 'AL000428': ('2018-12-04 11:32:00', '2018-12-04 16:02:00'),
 'AL000432': ('2019-01-13 17:33:00', '2019-01-13 19:10:00'),
 'AL000433': ('2019-01-14 17:29:00', '2019-01-14 18:19:00'),
 'AL000435': ('2019-01-15 15:13:30', '2019-01-15 16:21:00'),
 'AL000436': ('2019-01-16 09:11:00', '2019-01-16 09:37:30'),
 'AL000437': ('2019-01-16 11:32:30', '2019-01-16 12:18:00'),
 'AL000440': ('2019-01-21 10:51:00', '2019-01-21 11:55:30'),
 'AL000371': ('2018-10-28 22:26:30', '2018-10-28 23:31:00'),
 'AL000374': ('2018-10-31 09:40:00', '2018-10-31 11:14:00'),
 'AL000375': ('2018-10-31 13:24:00', '2018-10-31 14:14:00'),
 'AL000376': ('2018-11-01 17:35:00', '2018-11-01 18:54:00'),
 'AL000377': ('2018-11-02 17:57:00', '2018-11-02 18:34:00'),
 'AL000378': ('2018-11-02 20:10:00', '2018-11-02 21:14:00'),
 'AL000380': ('2018-11-04 16:23:00', '2018-11-04 17:48:00'),
 'AL000381': ('2018-11-07 11:30:00', '2018-11-07 13:58:30'),
 'AL000443': ('2019-02-02 17:40:00', '2019-02-02 18:37:30'),
 'AL000445': ('2019-02-03 12:22:30', '2019-02-03 14:12:00'),
 'AL000446': ('2019-02-04 16:35:00', '2019-02-04 17:24:00'),
 'AL000450': ('2019-02-02 19:20:00', '2019-02-02 21:33:00'),
 'AL000451': ('2019-02-07 06:42:00', '2019-02-07 07:04:00'),
 'AL000455': ('2019-02-08 08:59:00', '2019-02-08 10:09:00'),
 'AL000457': ('2019-02-10 13:57:00', '2019-02-10 15:32:00'),
 'AL000458': ('2019-02-11 07:21:00', '2019-02-11 08:10:30'),
 'AL000461': ('2019-02-12 12:22:00', '2019-02-12 14:20:00'),
 'AL000464': ('2019-02-14 10:42:30', '2019-02-14 11:28:00'),
 'AL000465': ('2019-02-23 07:18:00', '2019-02-23 08:25:00'),
 'AL000468': ('2019-02-25 16:30:00', '2019-02-25 18:10:00'),
 'AL000469': ('2019-02-25 21:10:00', '2019-02-25 23:53:00'),
 'AL000470': ('2019-02-26 05:00:00', '2019-02-26 06:13:00'),
 'AL000473': ('2019-03-18 12:37:30', '2019-03-18 13:04:00'),
 'AL000475': ('2019-03-21 18:03:00', '2019-03-21 18:48:00'),
 'AL000479': ('2019-03-28 19:15:00', '2019-03-28 19:57:00'),
 'AL000480': ('2019-03-28 20:32:00', '2019-03-28 21:08:00'),
 'AL000483': ('2019-04-02 21:34:00', '2019-04-02 22:31:30'),
 'AL000485': ('2019-04-05 13:55:00', '2019-04-05 15:20:00'),
 'AL000488': ('2019-04-07 03:23:30', '2019-04-07 04:50:00'),
 'AL000491': ('2019-04-09 10:16:00', '2019-04-09 12:17:30'),
 'AL000495': ('2019-04-11 17:42:30', '2019-04-11 18:24:00'),
 'AL000498': ('2019-04-13 23:23:30', '2019-04-14 00:18:30'),
 'AL000501': ('2019-04-15 15:10:30', '2019-04-15 16:15:00'),
 'AL000503': ('2019-04-21 14:35:00', '2019-04-21 17:48:00'),
 'AL000508': ('2019-04-24 19:01:00', '2019-04-24 21:02:30'),
 'AL000511': ('2019-04-27 01:48:00', '2019-04-27 04:18:00'),
 'AL000514': ('2019-04-28 16:49:00', '2019-04-28 18:40:00'),
 'AL000515': ('2019-04-28 23:23:00', '2019-04-28 23:56:00'),
 'AL000520': ('2019-05-05 16:24:30', '2019-05-05 17:00:00'),
 'AL000521': ('2019-05-05 23:43:00', '2019-05-06 00:08:00'),
 'AL000525': ('2019-05-07 11:53:30', '2019-05-07 12:52:30'),
 'AL000526': ('2019-05-08 10:18:00', '2019-05-08 12:00:30'),
 'AL000527': ('2019-05-08 14:35:00', '2019-05-08 15:36:30'),
 'AL000528': ('2019-05-09 20:02:00', '2019-05-09 22:55:00'),
 'AL000532': ('2019-05-14 05:01:30', '2019-05-14 05:53:00'),
 'AL000535': ('2019-05-16 13:21:00', '2019-05-16 14:12:30'),
 'AL000536': ('2019-05-16 16:43:00', '2019-05-16 18:27:00'),
 'AL000539': ('2019-05-21 13:40:00', '2019-05-21 15:16:00'),
 'AL000543': ('2019-05-22 11:41:30', '2019-05-22 12:38:00'),
 'AL000554': ('2019-05-28 08:23:30', '2019-05-28 09:52:00'),
 'AL000555': ('2019-05-28 18:13:30', '2019-05-28 19:27:00'),
 'AL000559': ('2019-06-01 16:45:00', '2019-06-01 18:30:00'),
 'AL000561': ('2019-06-01 22:50:30', '2019-06-02 01:11:30'),
 'AL000562': ('2019-06-02 07:28:30', '2019-06-02 08:05:30'),
 'AL000564': ('2019-06-04 03:51:00', '2019-06-04 05:26:00'),
 'AL000569': ('2019-06-06 15:49:00', '2019-06-06 16:43:00'),
 'AL000570': ('2019-06-07 10:11:00', '2019-06-07 10:47:00'),
 'AL000579': ('2019-06-12 10:35:30', '2019-06-12 12:16:00'),
 'AL000581': ('2019-06-14 09:47:00', '2019-06-14 11:23:00'),
 'AL000584': ('2019-06-17 16:08:00', '2019-06-17 17:41:00'),
 'AL000590': ('2019-06-20 10:04:30', '2019-06-20 10:53:00'),
 'AL000592': ('2019-06-20 21:39:00', '2019-06-20 22:22:00'),
 'AL000593': ('2019-06-22 12:45:00', '2019-06-22 14:29:30'),
 'AL000594': ('2019-06-24 15:17:30', '2019-06-24 15:54:00'),
 'AL000595': ('2019-06-25 10:51:00', '2019-06-25 12:46:00'),
 'AL000605': ('2019-07-02 11:50:00', '2019-07-02 14:05:00'),
 'AL000610': ('2019-07-05 21:04:30', '2019-07-05 21:35:30'),
 'AL000611': ('2019-07-06 09:49:00', '2019-07-06 11:20:00'),
 'AL000612': ('2019-07-07 10:32:30', '2019-07-07 12:08:00'),
 'AL000613': ('2019-07-10 09:56:00', '2019-07-10 11:51:00'),
 'AL000614': ('2019-07-10 17:46:00', '2019-07-10 18:08:00'),
 'AL000616': ('2019-07-14 00:41:30', '2019-07-14 01:51:00'),
 'AL000622': ('2019-08-01 22:06:00', '2019-08-02 00:19:00'),
 'AL000625': ('2019-08-04 07:08:00', '2019-08-04 08:52:30'),
 'AL000627': ('2019-08-05 11:27:00', '2019-08-05 12:54:00'),
 'AL000628': ('2019-08-06 18:58:00', '2019-08-06 21:25:00'),
 'AL000630': ('2019-08-07 19:15:00', '2019-08-07 19:37:00'),
 'AL000637': ('2019-08-14 11:03:00', '2019-08-14 11:43:30'),
 'AL000638': ('2019-08-14 13:44:30', '2019-08-14 15:09:00'),
 'AL000639': ('2019-08-16 06:50:00', '2019-08-16 07:35:46'),
 'AL000642': ('2019-08-17 15:45:30', '2019-08-17 16:23:30'),
 'AL000644': ('2019-08-21 23:02:00', '2019-08-21 23:46:30'),
 'AL000647': ('2019-08-24 02:11:00', '2019-08-24 03:34:00'),
 'AL000654': ('2019-08-27 12:57:00', '2019-08-27 13:36:00'),
 'AL000657': ('2019-08-28 14:59:00', '2019-08-28 16:05:00'),
 'AL000665': ('2019-08-30 09:20:00', '2019-08-30 10:21:30'),
 'AL000667': ('2019-09-04 06:28:00', '2019-09-04 07:19:00'),
 'AL000671': ('2019-09-05 15:00:30', '2019-09-05 15:33:00'),
 'AL000673': ('2019-09-06 18:10:30', '2019-09-06 18:45:00'),
 'AL000674': ('2019-09-07 16:13:00', '2019-09-07 17:32:30'),
 'AL000680': ('2019-09-13 20:16:30', '2019-09-13 21:16:00'),
 'AL000681': ('2019-09-14 01:37:00', '2019-09-14 02:19:00'),
 'AL000683': ('2019-09-16 08:24:30', '2019-09-16 09:23:30'),
 'AL000684': ('2019-09-16 12:04:00', '2019-09-16 14:27:00'),
 'AL000686': ('2019-09-16 21:08:30', '2019-09-16 22:28:00'),
 'AL000687': ('2019-09-17 04:44:30', '2019-09-17 06:13:00'),
 'AL000689': ('2019-09-19 08:56:00', '2019-09-19 10:29:30'),
 'AL000690': ('2019-09-22 05:19:00', '2019-09-22 06:29:00'),
 'AL000691': ('2019-09-22 15:42:30', '2019-09-22 17:28:00'),
 'AL000692': ('2019-09-22 19:06:00', '2019-09-22 20:18:00'),
 'AL000693': ('2019-09-23 09:10:30', '2019-09-23 10:39:30'),
 'AL000705': ('2019-12-07 15:21:30', '2019-12-07 15:34:30'),
 'AL000707': ('2019-12-10 09:46:30', '2019-12-10 10:14:00'),
 'AL000709': ('2019-12-11 14:07:00', '2019-12-11 16:08:00'),
 'AL000715': ('2019-12-14 10:32:30', '2019-12-14 10:58:30'),
 'AL000717': ('2019-12-14 17:27:30', '2019-12-14 17:58:30'),
 'AL000720': ('2019-12-16 18:56:00', '2019-12-16 19:59:30'),
 'AL000721': ('2019-12-17 15:56:00', '2019-12-17 17:02:00'),
 'AL000723': ('2019-12-19 02:17:00', '2019-12-19 04:05:00'),
 'AL000727': ('2019-12-20 13:15:30', '2019-12-20 14:33:00'),
 'AL000729': ('2019-12-21 00:08:30', '2019-12-21 02:10:00'),
 'AL000730': ('2019-12-26 18:54:30', '2019-12-26 19:17:00'),
 'AL000734': ('2020-01-04 12:40:00', '2020-01-04 13:21:00'),
 'AL000736': ('2020-01-05 07:31:00', '2020-01-05 09:13:00'),
 'AL000741': ('2020-01-11 06:30:00', '2020-01-11 07:11:30'),
 'AL000744': ('2020-01-11 21:38:30', '2020-01-11 22:29:00'),
 'AL000746': ('2020-01-13 13:11:00', '2020-01-13 13:44:00'),
 'AL000749': ('2020-01-15 02:38:30', '2020-01-15 03:29:00'),
 'AL000750': ('2020-01-15 13:22:00', '2020-01-15 13:55:30'),
 'AL000754': ('2020-01-19 06:38:00', '2020-01-19 07:29:00'),
 'AL000757': ('2020-01-22 08:24:00', '2020-01-22 09:04:00'),
 'AL000759': ('2020-01-27 18:53:00', '2020-01-27 20:43:30'),
 'AL000763': ('2020-01-29 14:39:30', '2020-01-29 16:05:00'),
 'AL000766': ('2020-01-31 13:33:30', '2020-01-31 13:59:30'),
 'AL000767': ('2020-01-31 14:30:30', '2020-01-31 15:43:00'),
 'AL000775': ('2020-02-04 10:36:30', '2020-02-04 11:19:00'),
 'AL000776': ('2020-02-04 20:31:00', '2020-02-04 21:28:30'),
 'AL000779': ('2020-02-07 15:04:30', '2020-02-07 15:59:30'),
 'AL000780': ('2020-02-09 13:13:00', '2020-02-09 14:55:30'),
 'AL000790': ('2020-02-14 15:02:00', '2020-02-14 15:48:30'),
 'AL000796': ('2020-02-22 17:11:00', '2020-02-22 19:01:30'),
 'AL000797': ('2020-02-23 08:12:00', '2020-02-23 08:49:30'),
 'AL000800': ('2020-02-26 15:27:00', '2020-02-26 17:54:00'),
 'AL000805': ('2020-03-01 13:30:00', '2020-03-01 13:59:00'),
 'AL000806': ('2020-03-02 07:38:30', '2020-03-02 08:45:00'),
 'AL000813': ('2020-03-06 02:59:00', '2020-03-06 04:55:00'),
 'AL000815': ('2020-03-06 10:10:30', '2020-03-06 12:34:30'),
 'AL000818': ('2020-03-09 13:09:30', '2020-03-09 13:43:00'),
 'AL000822': ('2020-03-13 11:12:30', '2020-03-13 12:37:30'),
 'AL000824': ('2020-03-13 21:36:00', '2020-03-13 21:53:00'),

In [41]:
len(limit)

418

print(sorted(set(vent_modes_ventilated.index) - set(limit)))

case = sorted(set(vent_modes_ventilated.index) - set(limit))[0]
index = cases.index(case)
index

vent_modes_ventilated.loc[case]

fig = plt.figure()
fig.set_size_inches(10, 8)
fig.subplots_adjust(left=None, bottom=None, right=None, top=None, wspace=None, hspace=0.05)

ax0 = fig.add_subplot(2, 1, 1)
data_pars_measurements[case]['VTemand_kg'].plot()
ax0.get_xaxis().set_visible(False)
ax0.set_ylabel('mL/kg', size = 12, color = 'black')
ax0.set_title(case,  size = 12, color = 'black')
ax0.legend(['VTemand_kg'], fontsize = 10, loc = 'best')
ax0.grid('on', linestyle='-', linewidth=0.5, color = 'gray')
ax0.tick_params(which = 'both', labelsize=12)

ax1 = fig.add_subplot(2, 1, 2)
data_pars_measurements[case]['PIP'].plot(color = 'red')
ax1.set_xlabel('Time', size = 12, color = 'black')
ax1.set_ylabel('cmH2O)', size = 12, color = 'black')
ax1.legend(['PIP'], fontsize = 10, loc = 'best')
ax1.grid('on', linestyle='-', linewidth=0.5, color = 'gray')
ax1.tick_params(which = 'both', labelsize=12)

limit[case] = eval("('%s', '%s')" % (data_pars_measurements[case].index[0], data_pars_measurements[case].index[-1]))
limit[case]

limit[case] = ('2020-06-23 14:15:00', '2020-06-23 14:15:05')

fig = plt.figure()
fig.set_size_inches(10, 8)
fig.subplots_adjust(left=None, bottom=None, right=None, top=None, wspace=None, hspace=0.05)

ax0 = fig.add_subplot(2, 1, 1)
data_pars_measurements[case]['VTemand_kg'][limit[case][0] : limit[case][1]].plot()
ax0.get_xaxis().set_visible(False)
ax0.set_ylabel('mL/kg', size = 12, color = 'black')
ax0.set_title(case,  size = 12, color = 'black')
ax0.legend(['VTemand_kg'], fontsize = 10, loc = 'best')
ax0.grid('on', linestyle='-', linewidth=0.5, color = 'gray')
ax0.tick_params(which = 'both', labelsize=12)

ax1 = fig.add_subplot(2, 1, 2)
data_pars_measurements[case]['PIP'][limit[case][0] : limit[case][1]].plot(color = 'red')
ax1.set_xlabel('Time', size = 12, color = 'black')
ax1.set_ylabel('cmH2O)', size = 12, color = 'black')
ax1.legend(['PIP'], fontsize = 10, loc = 'best')
ax1.grid('on', linestyle='-', linewidth=0.5, color = 'gray')
ax1.tick_params(which = 'both', labelsize=12)

In [153]:
with open(os.path.join(DATA_DUMP, 'limit_1_1100_ventilated.pickle'), 'wb') as handle:
    pickle.dump(limit, handle, protocol=pickle.HIGHEST_PROTOCOL)

### 7. Trim ventilator data using the manual filters

In [156]:
# Trim ventilator data using the manual filters
data_pars_measurements_ventilated = {}
data_pars_settings_ventilated = {}
data_pars_alarms_ventilated = {}

for case in vent_modes_ventilated.index:
    data_pars_measurements_ventilated[case] = data_pars_measurements[case][limit[case][0] : limit[case][1]]
    data_pars_settings_ventilated[case] = data_pars_settings[case][limit[case][0] : limit[case][1]]
    data_pars_alarms_ventilated[case] = data_pars_alarms[case][limit[case][0] : limit[case][1]]

### 8. Remove periods which stayed in some recordings when the ventilation was stopped

for patient, dta in data_pars_settings_ventilated.items():
    print(patient, sum(dta['Ventilation_stopped'] == 'yes'), )

In [159]:
data_pars_settings_ventilated['AL000428'][data_pars_settings_ventilated['AL000428']['Ventilation_stopped'] == 'yes'];

In [161]:
data_pars_measurements_ventilated['AL000428'].loc['2018-12-04 12:46:01': '2018-12-04 12:55:35'];

In [163]:
for case in data_pars_settings_ventilated:
    dta = data_pars_settings_ventilated[case]
    dta = dta[dta['Ventilation_stopped'] == 'no']
    data_pars_measurements_ventilated[case] = data_pars_measurements_ventilated[case].reindex(dta.index)
    data_pars_settings_ventilated[case] = data_pars_settings_ventilated[case].reindex(dta.index)
    data_pars_alarms_ventilated[case] = data_pars_alarms_ventilated[case].reindex(dta.index)

### 9. Remove any noninvasive parts accidentally remaining in the recording after manual trimming

In [165]:
mech_vent_modes = ['IPPV', 'SIPPV', 'SIMV', 'SIMVPSV', 'PSV']

for case in data_pars_settings_ventilated:
    dta = data_pars_settings_ventilated[case]
    dta = dta[dta['Ventilator_mode'].isin(mech_vent_modes)]
    data_pars_settings_ventilated[case] = dta

In [168]:
for case in data_pars_settings_ventilated:
    data_pars_measurements_ventilated[case] = data_pars_measurements_ventilated[case].reindex(data_pars_settings_ventilated[case].index)
    data_pars_alarms_ventilated[case] = data_pars_alarms_ventilated[case].reindex(data_pars_settings_ventilated[case].index)

### 10. Reanalyse the trimmed data as above

##### How many cases of the different ventilation modes occur?

In [172]:
vent_modes_ventilated = {}
for case in data_pars_settings_ventilated:
    # Multiply by two to get the number of seconds
    vent_modes_ventilated[case] = data_pars_settings_ventilated[case]['Ventilator_mode'].value_counts() * 2
    
vent_modes_ventilated = DataFrame(vent_modes_ventilated).T
vent_modes_ventilated.replace(np.nan, 0, inplace = True)

In [174]:
# Add VG data
VG = {}
for case in data_pars_settings_ventilated:
    try:
        # Multiply by two to get the number of seconds
        VG[case] = data_pars_settings_ventilated[case]['VG_state'].value_counts() * 2
    except KeyError:
        VG[case] = np.zeros(1)
        # print('No VG_state for %s' % case)
        
VG = DataFrame(VG).T
VG.columns = ['VG_off','VG_on']

vent_modes_ventilated = pd.concat([vent_modes_ventilated, VG], axis = 1)

In [176]:
# Add the total duration of the recordings
recording_duration_ventilated = {}
for case in data_pars_settings_ventilated:
    recording_duration_ventilated[case] = 2 * len(data_pars_settings_ventilated[case])

vent_modes_ventilated['total'] = Series(recording_duration_ventilated)
vent_modes_ventilated.sort_values('total')

          IPPV  PSV     SIMV  SIMVPSV    SIPPV   VG_off    VG_on  total
AL000629   0.0  0.0      0.0      0.0      0.0      NaN      NaN      0
AL000949   0.0  0.0      0.0      0.0      0.0      NaN      NaN      0
AL000518   0.0  0.0      0.0      0.0      0.0      NaN      NaN      0
AL000217   0.0  0.0      2.0      0.0      0.0      2.0      NaN      2
AL000492   0.0  0.0      4.0      0.0      0.0      4.0      NaN      4
...        ...  ...      ...      ...      ...      ...      ...    ...
AL000503   0.0  0.0  11580.0      0.0      0.0  11072.0    508.0  11580
AL000026   0.0  0.0  12122.0      0.0      0.0  12122.0      NaN  12122
AL000342   0.0  0.0  12900.0      0.0      0.0  12900.0      NaN  12900
AL000113   0.0  0.0  14208.0      0.0      0.0     10.0  14198.0  14208
AL000428   0.0  0.0      0.0      0.0  15718.0    262.0  15456.0  15718

[418 rows x 8 columns]

### 11. Only keep recordings that have at least 10 minutes (600 seconds) mechanical ventilation after manual trimming

In [179]:
vent_modes_ventilated = vent_modes_ventilated[vent_modes_ventilated['total'] >= 600]
cases = sorted(vent_modes_ventilated.index)
len(vent_modes_ventilated), len(cases)

(407, 407)

In [181]:
# How many seconds of each ventilation mode in total?
total_duration_ventilated = DataFrame(vent_modes_ventilated.sum(axis = 0), columns = ['duration (seconds)'])
total_duration_ventilated

         duration (seconds)
IPPV                47704.0
PSV                   208.0
SIMV              1042124.0
SIMVPSV             82824.0
SIPPV              554390.0
VG_off             475686.0
VG_on             1251564.0
total             1727250.0

In [183]:
print('SIMV:', sum(vent_modes_ventilated['SIMV'] > 0))
print('SIPPV:', sum(vent_modes_ventilated['SIPPV'] > 0))
print('SIMVPSV:', sum(vent_modes_ventilated['SIMVPSV'] > 0))
print('PSV:', sum(vent_modes_ventilated['PSV'] > 0))
print('IPPV:', sum(vent_modes_ventilated['IPPV'] > 0))
print('VG_on:', sum(vent_modes_ventilated['VG_on'] > 0))
print('total', len(vent_modes_ventilated))

SIMV: 261
SIPPV: 157
SIMVPSV: 29
PSV: 1
IPPV: 23
VG_on: 315
total 407

In [185]:
data_pars_measurements_ventilated = {rec : data_pars_measurements_ventilated[rec] for rec 
                                     in data_pars_measurements_ventilated if rec in vent_modes_ventilated.index}
data_pars_settings_ventilated = {rec : data_pars_settings_ventilated[rec] for rec 
                                     in data_pars_settings_ventilated if rec in vent_modes_ventilated.index}
data_pars_alarms_ventilated = {rec : data_pars_alarms_ventilated[rec] for rec 
                                     in data_pars_alarms_ventilated if rec in vent_modes_ventilated.index}
len(data_pars_measurements_ventilated), len(data_pars_settings_ventilated), len(data_pars_alarms_ventilated)

(407, 407, 407)

### 12. Export trimmed ventilator data as pickle archives

In [188]:
with open(os.path.join(DATA_DUMP, 'data_pars_measurements_ventilated_1_1100.pickle'), 'wb') as handle:
    pickle.dump(data_pars_measurements_ventilated, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open(os.path.join(DATA_DUMP, 'data_pars_settings_ventilated_1_1100.pickle'), 'wb') as handle:
    pickle.dump(data_pars_settings_ventilated, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open(os.path.join(DATA_DUMP, 'data_pars_alarms_ventilated_1_1100.pickle'), 'wb') as handle:
    pickle.dump(data_pars_alarms_ventilated, handle, protocol=pickle.HIGHEST_PROTOCOL)

### 13. Export data about ventilator modes to Excel files and pickle archives

In [191]:
writer = pd.ExcelWriter(os.path.join(DIR_WRITE, 'ventilation_modes_ventilated_1_1100.xlsx'))
vent_modes_ventilated.to_excel(writer, 'vent_modes_ventilated_1_1100')
total_duration_ventilated.to_excel(writer, 'total_duration_vent_1_1100')
writer.close()

In [193]:
with open(os.path.join(DATA_DUMP, 'vent_modes_ventilated_1_1100.pickle'), 'wb') as handle:
    pickle.dump(vent_modes_ventilated, handle, protocol=pickle.HIGHEST_PROTOCOL)